Repository Quansight-Labs/quansight-labs-site, pull requests merged in 2020-02, with the labels that each got.

#46 PR: Add non-blog config and some initial pages
  conf.py
  pages/about.rst
  pages/index.rst
Labels: website

#44 Spyder terminal blog
  images/spyder-terminal/bash.png
  images/spyder-terminal/cursor-style.png
  images/spyder-terminal/minimal.png
  images/spyder-terminal/new-term.gif
  images/spyder-terminal/preferences.png
  images/spyder-terminal/shells.png
  images/spyder-terminal/shortcuts.png
  images/spyder-terminal/spyder-dark.png
  images/spyder-terminal/tcsh.png
  images/spyder-terminal/terminal-colors.gif
  posts/2020/02/Spyder-terminal.md
Labels: content

#48 Fix issue with disappearing images in Spyder-Terminal blog post
  posts/2020/02/Spyder-terminal.md
Labels: bug

#51 Add Mars's first blog post
  images/codesprite-comics/CodeSprite-part-1.png
  images/codesprite-comics/CodeSprite-part-2.png
  images/codesprite-comics/My-Unexpected-Dive-Into-Open-Source-Python-Illustration.png
  images/codesprite-comics/PyData-Lightning-Talk.png
  images/codesprite-comics/PyData-NYC-Banner.jpg
  posts/2020/02/my-unexpected-dive-into-open-source-python.md
Labels: content

#50 PR: Initial gallery support for pages
  .gitignore
  conf.py
  galleries/projects/altair-logo-light.png
  galleries/projects/dask.png
  galleries/projects/metadata.yml
  galleries/projects/numba-blue-horizontal-rgb.svg
  galleries/projects/pyviz.png
  galleries/projects/scipy.png
  galleries/projects/spyder.svg
  galleries/projects/sympy.png
  pages/projects.rst
  plugins/__init__.py
  plugins/gallery_directive/README.md
  plugins/gallery_directive/gallery_directive.plugin
  plugins/gallery_directive/gallery_directive.py
  plugins/gallery_directive/templates/jinja/gallery_directive.tmpl
  plugins/gallery_directive/templates/mako/gallery_directive.tmpl
  themes/quansightlabs/templates/gallery_directive.tmpl
Labels: enhancement
