Repository Quansight-Labs/quansight-labs-site, pull requests merged in 2020-09, with the labels that each got.

#124 PR: Add new team members
  galleries/team/kim_pevey.jpg
  galleries/team/metadata.yml
  galleries/team/pam_wadhwa.jpeg
  galleries/team/tony_fast.png
Labels: task

#125 Fix build that was broken by a Nikola dependency update
  .circleci/config.yml
  requirements.txt
Labels: maintenance

#127 CI: fix the deploy build on CircleCI as well
  .circleci/config.yml
Labels: maintenance

#118 Added post about performance of the Versioned HDF5 library.
  images/versioned-hdf5-performance/create_test1.png
  images/versioned-hdf5-performance/create_test2.png
  images/versioned-hdf5-performance/create_test3.png
  images/versioned-hdf5-performance/create_test4.png
  images/versioned-hdf5-performance/create_test5.png
  images/versioned-hdf5-performance/filesizes.png
  images/versioned-hdf5-performance/filesizes_test5.png
  images/versioned-hdf5-performance/latestread.png
  images/versioned-hdf5-performance/legend.png
  images/versioned-hdf5-performance/seqread.png
  images/versioned-hdf5-performance/write_times_test1.png
  images/versioned-hdf5-performance/write_times_test2.png
  images/versioned-hdf5-performance/write_times_test3.png
  images/versioned-hdf5-performance/write_times_test4.png
  images/versioned-hdf5-performance/write_times_test5.png
  posts/2020/09/versioned-hdf5-performance.md
Labels: content

#123 Add a blog post on the design of versioned-hdf5
  images/versioned-hdf5-design-1.svg
  images/versioned-hdf5-design-2.svg
  posts/2020/09/design-of-the-versioned-hdf5-library.markdown
Labels: content
