Repository Quansight-Labs/quansight-labs-site, pull requests merged in 2020-07, with the labels that each got.

#82 PR: Add Spyder tutorials blogpost
  posts/2020/07/writing-docs-is-not-just-writing-docs.md
Labels: content

#77 nixos wifi router blog post
  conf.py
  posts/2020/06/nixos-rpi-wifi-router.md
Labels: content

#88 Pin Nikola version to 8.0.4 in requirements.txt
  requirements.txt
Labels: maintenance

#79 add post about me working at quansight
  posts/2020/07/Three-months-and-having-fun.md
Labels: content

#91 Update Projects and Team pages
  galleries/new_projects/metadata.yml
  galleries/projects/ignite_logo.svg
  galleries/projects/metadata.yml
  galleries/projects/numpy.png
  galleries/projects/numpylogo.svg
  galleries/projects/scipy.png
  galleries/projects/zarr.png
  galleries/team/james_bourbeau.png
  galleries/team/metadata.yml
  galleries/team/victor_fomin.jpg
Labels: content

#94 Some more updates to listed projects we actively support.
  galleries/projects/altair-logo-light.png
  galleries/projects/holoviz_logo.svg
  galleries/projects/metadata.yml
  galleries/projects/pytables.png
  galleries/projects/pyviz.png
  galleries/team/metadata.yml
Labels: content

#93 Add sponsor logos at the bottom of the front page
  images/sponsors.png
  pages/index.rst
Labels: content

#95 Content for about page and front page
  pages/about.rst
  pages/index.rst
Labels: content

#104 PR: Update sponsors logos
  images/sponsors.png
  images/sponsors/sponsors.svg
Labels: website
