Repository Quansight-Labs/quansight-labs-site, pull requests merged in 2021-11, with the labels that each got.

#271 modify labs styling
  themes/quansightlabs/assets/css/custom.css
  themes/quansightlabs/templates/index.tmpl
Labels: type: enhancement 💅🏼, type: design 🎨, PR: merge-ready ✅

#279 :rocket: Update settings for Netlify deploy
  .github/workflows/deploy.yml
  .gitignore
  README.md
  images/readme-build-previews.png
  images/readme_PR_checks.png
  images/readme_preview_deploy.png
  netlify.toml
  nikolaserve.pid
  runtime.txt
Labels: type: dependencies 📦, type: deployment 🚀, PR: review-ready 👀

#282 reduce h1, h2 font size
  themes/quansightlabs/assets/css/custom.css
Labels: type: design 🎨

#278 SciPy and scikits backend extensibility
  images/2021/11/CuPy_support_scipy_scikits_with_details.png
  images/2021/11/nep-0047-library-dependencies.png
  images/2021/11/scipy-ndimage-dispatcher.png
  images/2021/11/scipy-numpy-dispatch.png
  images/sponsors/AMD_E_Blk_RGB.png
  posts/2021/11/pydata-extensibility-vision.md
Labels: type: content 📝

#283 Update link in pydata-extensibility-vision.md
  posts/2021/11/pydata-extensibility-vision.md
Labels: type: maintenance 🚧
