Repository Quansight-Labs/quansight-labs-site, pull requests merged in 2021-08, with the labels that each got.

#223 Enable utterances (comment system) on the blog.
  conf.py
Labels: type: enhancement 💅🏼, PR: in-rewview 🔎

#217 [Jul 30] Running benchmarks on GitHub Actions
  images/2021/08/github-actions-benchmark-no-interleaving.png
  images/2021/08/github-actions-benchmark-single-process.png
  images/2021/08/github-actions-benchmark.png
  posts/2021/08/github-actions-benchmarks.md
Labels: type: content 📝, PR: review-ready 👀

#230 Add link to schedule in the readme.
  README.md
Labels: type: enhancement 💅🏼

#231 :pencil2: Fix publishing date - move backward
  posts/2021/08/github-actions-benchmarks.md
Labels: type: content 📝, PR: review-ready 👀

#232 galleries/team: add Filipe Laíns (FFY00)
  galleries/team/filipe_lains.png
  galleries/team/metadata.yml
Labels: type: content 📝

#233 :memo: Fix deploy instructions
  README.md
  images/readme-build-previews.png
Labels: PR: review-ready 👀

#236 Fix author listing on EOSS cycle 4 blog post
  posts/2021/08/czi-eoss4-grants-at-quansight-labs.md
Labels: type: content 📝, type: maintenance 🚧
