Repository Quansight-Labs/quansight-labs-site, pull requests merged in 2021-07, with the labels that each got.

#212 [July 7] pyflyby blog post
  images/2021/08/jlpfb.gif
  images/2021/08/pfb-autoimport.gif
  images/2021/08/py-exec-matplotlib.png
  posts/2021/08/better-interractive-jupyter-session-with-pyflyby.md
Labels: PR: review-ready 👀, type: content 📝

#218 Allow to manually trigger rebuild
  .github/workflows/deploy.yml
Labels: type: deployment 🚀

#221 ENH Supports multiple authors
  conf.py
  posts/2020/11/design_in_open_source.md
  posts/2020/12/jupyterlab-winter-theme.md
  posts/2021/04/spot-the-differences.md
  posts/2021/07/better-interractive-jupyter-session-with-pyflyby.md
  requirements.txt
  themes/quansightlabs/templates/index.tmpl
  themes/quansightlabs/templates/post_header.tmpl
Labels: type: enhancement 💅🏼

#222 Add blog post on PyTorch-Ignite Code Generator
  images/pytorch-ignite/code-generator/code-generator-preview.png
  posts/2021/07/introducing-code-generator-v020.md
Labels: type: content 📝

#224 Add post on moving SciPy to Meson
  images/2021/07/ninjabuild_tracing_12jobs.png
  images/2021/07/scipy_build_dependencies.png
  posts/2021/07/moving-scipy-to-meson.md
Labels: type: content 📝

#225 Add myself to Quansight Labs 🥳
  galleries/team/metadata.yml
  galleries/team/saul_shanabrook.jpeg
Labels: type: content 📝

#226 Minor wording fix, use "pyproject.toml-based builds", no PEP xxx
  posts/2021/07/moving-scipy-to-meson.md
Labels: type: content 📝
