Repository Quansight-Labs/quansight-labs-site, pull requests merged in 2021-02, with the labels that each got.

#155 Added new logo and colors according to branding guide.
  conf.py
  files/images/QuansightLabs_logo_V1_white.png
  themes/quansightlabs/assets/css/custom.css
Labels: website

#161 Fix inconsistent dependencies after today's Dependabot merges
  requirements.txt
Labels: dependencies

#152 Numba dynamic guvectorize post
  posts/2021/02/enhancements-to-numba-guvectorize-decorator.md
Labels: content
