Repository Quansight-Labs/quansight-labs-site, pull requests merged in 2021-05, with the labels that each got.

#193 STY Use left justify left for post index
  themes/quansightlabs/assets/css/custom.css
Labels: design

#184 Add papyri post
  images/2021/05/numpy-linspace-compare.png
  images/2021/05/papyri-1.png
  images/2021/05/papyri-nav.gif
  images/2021/05/papyri-terminal-fig.png
  posts/2021/05/rethinking-jupyter-documentation.md
Labels: content

#194 Build website using github action.
  .circleci/config.yml
  .github/workflows/deploy.yml
Labels: deployment

#196 Rebuild the website daily.
  .github/workflows/deploy.yml
Labels: deployment

#177 JupyterLab accessibility post 2
  images/jlabaccess2.png
  posts/2021/05/putting-out-the-fire.md
Labels: content

#199 STY Makes the header consistent between posts and other pages
  themes/quansightlabs/assets/css/quansightlabs.css
Labels: design

#201 ENH Adds description into the metatags
  pages/about.rst
  pages/index.rst
  pages/projects.rst
  pages/team.rst
  themes/quansightlabs/templates/post_header.tmpl
  themes/quansightlabs/templates/post_ipynb.tmpl
Labels: maintenance
