Repository Quansight-Labs/quansight-labs-site, pull requests merged in 2021-09, with the labels that each got.

#238 ENH Adds taller image for social media
  files/images/QuansightLabs_logo_V2_rect.png
  themes/quansightlabs/templates/post_helper.tmpl
Labels: type: design 🎨

#241 Team catalogue update [Sayantika Banik]
  galleries/team/metadata.yml
  galleries/team/sayantika_banik.jpeg
Labels: type: content 📝

#227 Add blog post: NumPy's accessibility
  images/2021/07/numpy-accessibility/color_deficiency.png
  images/2021/07/numpy-accessibility/compliance_levels.png
  images/2021/07/numpy-accessibility/disability_not_recognized.png
  images/2021/07/numpy-accessibility/header_image.png
  images/2021/07/numpy-accessibility/situation_disability.png
  images/2021/07/numpy-accessibility/types_of_disabilities.png
  images/2021/07/numpy-accessibility/venn_diagram.png
  images/2021/07/numpy-accessibility/wave_extension.png
  posts/2021/07/numpy-accessibility-guidelines.md
Labels: type: content 📝, PR: review-ready 👀

#243 team: Add Rohit Goswami
  galleries/team/metadata.yml
  galleries/team/rohit_goswami.jpg
Labels: type: content 📝

#240 Add blog post accessibility checklist
  .github/pull_request_template.md
Labels: type: enhancement 💅🏼, PR: merge-ready ✅

#229 JupyterLab Accessibility post 3
  posts/2021/09/not-a-checklist.md
Labels: type: content 📝, PR: review-ready 👀, PR: in-review 🔎

#253 Add teaser end tag Jupyter Accessibility Post 3
  posts/2021/09/not-a-checklist.md
Labels: type: maintenance 🚧

#250 :construction_worker: Add pa11y tests
  .github/workflows/pa11y_tests.yml
  .pa11yci
  nikolaserve.pid
  package-lock.json
  package.json
Labels: type: enhancement 💅🏼, type: deployment 🚀, type: accessibility ♿️

#228 Alt text low code post
  posts/2021/09/low-code-workshop.md
Labels: type: content 📝

#263 Remove redundant markdown header in the recent low-code post
  posts/2021/09/low-code-workshop.md
Labels: type: maintenance 🚧
