Repository Quansight-Labs/quansight-labs-site, pull requests merged in 2021-04, with the labels that each got.

#156 Add PyTorch TensorIterator update post
  posts/2020/04/pytorch-tensoriterator-internals.md
  posts/2021/04/pytorch-tensoriterator-internals-update.md
Labels: content

#179 Fix example 5 code
  posts/2021/04/pytorch-tensoriterator-internals-update.md
Labels: content, maintenance

#181 Assume 'make build' is run after 'pip install -r requirements.txt'
  .circleci/config.yml
  .gitignore
  Makefile
  plugins/localsearch/MIT-LICENSE.txt
  plugins/localsearch/README.md
  plugins/localsearch/conf.py.sample
  plugins/localsearch/conf.py.sample.alt
  plugins/localsearch/localsearch.plugin
  plugins/localsearch/localsearch/__init__.py
  plugins/localsearch/localsearch/files/assets/css/img/loader.gif
  plugins/localsearch/localsearch/files/assets/css/img/search.png
  plugins/localsearch/localsearch/files/assets/css/tipuesearch.css
  plugins/localsearch/localsearch/files/assets/js/tipuesearch.js
  plugins/localsearch/localsearch/files/assets/js/tipuesearch.min.js
  plugins/localsearch/localsearch/files/assets/js/tipuesearch_set.js
  plugins/localsearch/localsearch/templates/jinja/localsearch.tmpl
  plugins/localsearch/localsearch/templates/mako/localsearch.tmpl
  plugins/localsearch/search-EXAMPLE.html
Labels: maintenance

#182 Fix deployment to GitHub, remove stray venv command
  .circleci/config.yml
Labels: deployment, maintenance

#180 Add blogpost on psf grant
  posts/2021/04/a-step-towards-educating-with-Spyder.md
Labels: content

#189 PR: Add LG logo to the sponsors
  images/sponsors.png
  images/sponsors/LG Electronics 3D CMYK.png
  images/sponsors/sponsors.svg
Labels: content

#190 PR: Add new quansight logo
  images/sponsors.png
  images/sponsors/Quansight_Logo.png
  images/sponsors/czi.png
  images/sponsors/jax.png
  images/sponsors/omni_sci.jpg
  images/sponsors/sponsors.svg
  images/sponsors/tdk.png
Labels: website
