Repository Quansight-Labs/quansight-labs-site, pull requests merged in 2021-03, with the labels that each got.

#168 Add ndindex to the list of projects
  galleries/projects/metadata.yml
  galleries/projects/ndindex.svg
Labels: content

#167 Add the localsearch plugin
  .circleci/config.yml
  .gitignore
  Makefile
  conf.py
  pages/search.html
  requirements.txt
Labels: enhancement

#172 fix circleci deploy step
  .circleci/config.yml
Labels: deployment

#173 activate the venv since 'deploy' requires PATH modification
  .circleci/config.yml
Labels: deployment

#160 (CU-cz3mye) JupyterLab Accessibility post 1
  images/jlabaccess1.png
  posts/2021/03/accessibility-whos-responsible.md
Labels: content
