Repository Quansight-Labs/quansight-labs-site, pull requests merged in 2022-01, with the labels that each got.

#290 :construction_worker: Update netlify.toml to add preview of future posts
  netlify.toml
Labels: type: enhancement 💅🏼, type: deployment 🚀

#291 :busts_in_silhouette: Update team section
  galleries/team/metadata.yml
Labels: type: maintenance 🚧

#289 IPython 8
  posts/2022/01/ipython-8.0-lessons-learned-maintaining-software.md
Labels: type: content 📝

#293 :arrow_up: More dependencies
  requirements.txt
Labels: type: maintenance 🚧, type: dependencies 📦

#295 Adds Cristian Garcia to team
  galleries/team/cristian_garcia.jpg
  galleries/team/metadata.yml
Labels: type: content 📝

#297 Add Pamphile Roy to Team page
  galleries/team/metadata.yml
  galleries/team/pamphile_roy.jpg
Labels: type: content 📝

#285 Added internship wrap blog about Grayskull
  images/2022/01/conda-build.png
  images/2022/01/ensureconda.gif
  images/2022/01/grayskull.jpg
  images/2022/01/package_name.png
  images/2022/01/recipe_animation.png
  posts/2022/01/conda-grayskull-packaging.md
Labels: type: content 📝, PR: merge-ready ✅
